site_name: datafunctions

theme:
  name: material
  logo: assets/images/superhero_logo_white.png
  favicon: assets/images/superhero_logo.png

nav:
  - 'index.md'
  - 'core_functions.md'
  # - 'advanced_functions.md'
  # - 'cloud_functions.md'
  # - 'python_package.md'
  # - 'tutorials.md'

repo_url: https://github.com/datafunctions/datafunctions.github.io

google_analytics:
  - UA-119865580-4
  - auto

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@beepbeep.technology

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      use_pygments: true

  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.tabbed
  - pymdownx.superfences
